# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp215f-dk.dtb \
	stm32mp235f-dk.dtb \
	stm32mp253f-bytedevkit-v1.dtb \
	stm32mp253f-bytedevkit-v2.dtb \
	stm32mp257f-bytedevkit-v1.dtb \
	stm32mp257f-bytedevkit-v2.dtb \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb
